---
cache:
  bundler: true
language: ruby
rvm:
- 2.4.6
- 2.5.5
- 2.6.3
before_install:
- rvm use @global
- gem uninstall bundler -x || true
- gem install bundler --force --version=2.0.1
- bundler --version
- bundle install
script:
- bundle exec rspec
- bundle exec rubocop --fail-level C
